CREATE SCHEMA `bookmanager` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE `bookmanager`.`books` (
  `ID` INT(11) NOT NULL,
  `BOOK_TITLE` VARCHAR(255) NOT NULL,
  `BOOK_AUTHOR` VARCHAR(255) NOT NULL,
  `BOOK_PRICE` INT(11) NOT NULL,
  PRIMARY KEY (`ID`));

ALTER TABLE `bookmanager`.`books`
  CHANGE COLUMN `ID` `ID` INT(11) NOT NULL AUTO_INCREMENT ;